# Generated by Django 6.0.3 on 2026-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_servicejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
