# Generated by Django 6.0.3 on 2026-03-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0003_servicejob_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
