# Generated by Django 6.0.3 on 2026-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0007_alter_payment_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="mechanic_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicejob",
            name="service_image",
            field=models.ImageField(blank=True, null=True, upload_to="service_pics/"),
        ),
    ]
