# Generated by Django 6.0.3 on 2026-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0008_servicejob_mechanic_notes_servicejob_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
