# Generated by Django 6.0.3 on 2026-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_servicejob_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="estimated_completion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicejob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
