# Generated by Django 6.0.3 on 2026-03-27 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0010_servicejob_estimated_completion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicejob",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
