# Generated by Django 6.0.3 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0011_servicejob_feedback_servicejob_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicejob",
            name="next_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicejob",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
